# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmap',
            name='shortcode',
            field=models.CharField(default='test', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
