# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_urlmap_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='shortcode',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
